"""Schema layer: the contracts every other module is written against.

Import from here rather than from the submodules -- the split between
``land_record``, ``llm_contract`` and ``artifact`` is an implementation detail, and
keeping one import surface makes the boundary between "wire" and "domain" types the
only distinction callers have to hold in mind.
"""

from __future__ import annotations

from .artifact import (
    SCHEMA_VERSION,
    ExtractionArtifact,
    FieldProvenance,
    ProcessingMetadata,
    SourceDocument,
    TokenUsage,
)
from .enums import (
    VERNACULAR_ALIASES,
    CultivabilityClass,
    EncumbranceStatus,
    EncumbranceType,
    ExtractorKind,
    IrrigationSource,
    LandClassification,
    MutationStatus,
    MutationType,
    RecordFormat,
    RelationType,
    TenureType,
    cultivability_of,
)
from .geo import (
    AreaComparison,
    ConfidenceBreakdown,
    ConfidenceWeights,
    DiscrepancyReport,
    GeometrySource,
    MismatchBand,
    ParcelGeometry,
    RecommendedAction,
    TopologyFinding,
    TopologyKind,
)
from .land_record import (
    ClassifiedArea,
    CropEntry,
    Encumbrance,
    Jurisdiction,
    LandParcelRecord,
    MutationEntry,
    OwnerRecord,
    OwnershipShare,
    PersonName,
    SubDivision,
)
from .llm_contract import (
    FieldConfidence,
    LlmArea,
    LlmClassifiedArea,
    LlmCrop,
    LlmEncumbrance,
    LlmExtraction,
    LlmJurisdiction,
    LlmMutation,
    LlmOwner,
    LlmParcel,
    LlmPerson,
    LlmShare,
    LlmSubDivision,
    UnreadableRegion,
)
from .ocr import BoundingBox, OcrLine, OcrToken, PageOcr, ScriptHistogram, TableCell, TableGrid
from .units import (
    BIGHA_REGISTRY,
    SQ_METRE_PER_UNIT,
    AmbiguousUnitError,
    AreaMeasurement,
    AreaUnit,
    AreaUnitSystem,
    BighaDefinition,
    UnitConversionError,
    sum_areas,
)
from .validation import (
    RuleCode,
    RuleTolerance,
    Severity,
    ValidationIssue,
    ValidationPolicy,
    ValidationReport,
)

__all__ = [
    "BIGHA_REGISTRY",
    "SCHEMA_VERSION",
    "SQ_METRE_PER_UNIT",
    "VERNACULAR_ALIASES",
    "AmbiguousUnitError",
    "AreaComparison",
    "AreaMeasurement",
    "AreaUnit",
    "AreaUnitSystem",
    "BighaDefinition",
    "BoundingBox",
    "ClassifiedArea",
    "ConfidenceBreakdown",
    "ConfidenceWeights",
    "CropEntry",
    "CultivabilityClass",
    "DiscrepancyReport",
    "Encumbrance",
    "EncumbranceStatus",
    "EncumbranceType",
    "ExtractionArtifact",
    "ExtractorKind",
    "FieldConfidence",
    "FieldProvenance",
    "GeometrySource",
    "IrrigationSource",
    "Jurisdiction",
    "LandClassification",
    "LandParcelRecord",
    "LlmArea",
    "LlmClassifiedArea",
    "LlmCrop",
    "LlmEncumbrance",
    "LlmExtraction",
    "LlmJurisdiction",
    "LlmMutation",
    "LlmOwner",
    "LlmParcel",
    "LlmPerson",
    "LlmShare",
    "LlmSubDivision",
    "MismatchBand",
    "MutationEntry",
    "MutationStatus",
    "MutationType",
    "OcrLine",
    "OcrToken",
    "OwnerRecord",
    "OwnershipShare",
    "PageOcr",
    "ParcelGeometry",
    "PersonName",
    "ProcessingMetadata",
    "RecommendedAction",
    "RecordFormat",
    "RelationType",
    "RuleCode",
    "RuleTolerance",
    "ScriptHistogram",
    "Severity",
    "SourceDocument",
    "SubDivision",
    "TableCell",
    "TableGrid",
    "TenureType",
    "TokenUsage",
    "TopologyFinding",
    "TopologyKind",
    "UnitConversionError",
    "UnreadableRegion",
    "ValidationIssue",
    "ValidationPolicy",
    "ValidationReport",
    "cultivability_of",
    "sum_areas",
]
